### PR TITLE
Change API key, quick fix

### PR DESCRIPTION
**Pull request by cnbeining**
I just put a quick fix so everyone can use it for now.

Hoping this can give us some time to work around this issue.

```
$ ./bilidan.py http://www.bilibili.com/video/av899574/
-ERROR: Automatically downloading 'danmaku2ass.py'
       from https://github.com/m13253/danmaku2ass
       to /Users/Beining/Documents/coding/BiliDan/danmaku2ass.py
INFO: Loading video info...
INFO: Got video cid: 1445374
INFO: Loading video content...
INFO: Got media URLs:
      1: http://edge.v.iask.com/127734380.hlv?KID=sina,viask&Expires=1457884800&ssig=aj1xDQzV8C
      2: http://edge.v.iask.com/127734384.hlv?KID=sina,viask&Expires=1457884800&ssig=dtnMrZAavW
INFO: Determining video resolution...
^C
```

### CODE REVIEW

**Comment by zanderzhng** [comment]
Working confirmed.

**Comment by m13253** [comment]
Thank you a lot!
But, why are you committing 2 files?

**Comment by cnbeining** [comment]
A .gitignore wouldn't hurt you.

2016年3月12日星期六，Star Brilliant <notifications@github.com> 写道：

**Comment by m13253** [comment]
It's always better to separate them.

**Comment by cnbeining** [comment]
OK. One sec.

2016年3月12日星期六，Star Brilliant <notifications@github.com> 写道：

**Pull request merged**
